spring:
  mail:
    host: smtp.gmail.com
    username: rahilthakkar52@gmail.com
    password: krhrbiugmzmwoobi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587
