spring:
  mail:
    host: smtp.gmail.com
    username: youremail
    password: smtppass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587
